[workspace]
resolver = "2"
members = [
    "extractous-core",
    "bindings/extractous-python",
]

[workspace.package]
version = "0.2.1"
edition = "2021"
authors = ["Yobix AI <dev@yobix.ai>"]
license = "Apache-2.0"

[profile.release]
opt-level = 3
lto = "thin"
rpath = true
